[package]
name = "kuso-subdomain-adder"
version = "0.1.0"
authors = ["sksat <sksat@sksat.net>"]
edition = "2018"

license = "MIT"

[dependencies]
actix-web = "3.3.2"
cloudflare = "0.7.2"
punycode = "0.4.1"
serde = "1.0.118"
serde_derive = "1.0.118"
toml = "0.5.8"
