[package]
name = "kuso-subdomain-adder"
version = "0.3.2"
authors = ["sksat <sksat@sksat.net>"]
edition = "2018"

license = "MIT"

[dependencies]
actix-web = "4.0.0-beta.6"
clap = "2.33.3"
cloudflare = "0.8.2"
env_logger = "0.8.4"
lazy_static = "1.4.0"
log = "0.4.14"
punycode = "0.4.1"
serde = "1.0.126"
serde_derive = "1.0.126"
tera = "1.10.0"
toml = "0.5.8"
